[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyXLMS"
version = "1.8.11"
authors = [
  { name="Micha Johannes Birklbauer", email="micha.birklbauer@fh-hagenberg.at" },
]
maintainers = [
  { name="Micha Johannes Birklbauer", email="micha.birklbauer@fh-hagenberg.at" },
]
readme = "README.md"
license = {file = "LICENSE"}
description = "A python package to process protein cross-linking data."
keywords = ["crosslink", "crosslinker", "crosslinking", "mass spectrometry", "proteomics"]
requires-python = ">=3.14"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering :: Bio-Informatics",
  "Development Status :: 5 - Production/Stable"
]
dependencies = [
    "biopandas>=0.5.1",
    "biopython>=1.87",
    "lxml>=6.1.0",
    "matplotlib>=3.10.9",
    "matplotlib-venn>=1.1.2",
    "numpy>=2.4.4",
    "openpyxl>=3.1.5",
    "pandas>=3.0.3",
    "pyarrow>=24.0.0",
    "pydantic>=2.13.4",
    "pyteomics[xml]==4.7.5",
    "requests>=2.34.1",
    "tqdm>=4.67.3",
]

[project.optional-dependencies]
docs = [
  "sphinx",
  "pydata-sphinx-theme",
  "myst-parser",
  "sphinx-copybutton"
]
dev = [
  "jupyterlab",
  "sphinx",
  "pydata-sphinx-theme",
  "myst-parser",
  "sphinx-copybutton",
  "uv",
  "ty",
  "ruff",
  "pyright",
  "pytest",
  "pytest-cov"
]

[project.urls]
Homepage = "https://hgb-bin-proteomics.github.io/pyXLMS-pydantic"
Documentation = "https://hgb-bin-proteomics.github.io/pyXLMS-pydantic"
Repository = "https://github.com/hgb-bin-proteomics/pyXLMS-pydantic.git"
Issues = "https://github.com/hgb-bin-proteomics/pyXLMS/issues"
